/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_Types.h"
#include "common_macros.h"

#define 	RCC_BASE  				0x40021000
#define 	GPIOA_BASE  			0x40010800
#define		EXTI_BASE				0x40010400
#define		AFIO_BASE				0x40010000

#define 	APB2ENR			(volatile R32_Register *)  (RCC_BASE + 0x18)
#define 	GPIOA_CRL		(volatile R32_Register *)  (GPIOA_BASE)
#define 	GPIOA_CRH		(volatile R32_Register *)  (GPIOA_BASE + 0x04)
#define 	GPIOA_ODR		(volatile R32_Register *)  (GPIOA_BASE + 0x0C)

#define 	EXTI_IMR		(volatile R32_Register *)  (EXTI_BASE)
#define  	EXTI_RTSR		(volatile R32_Register *)  (EXTI_BASE + 0x08)
#define 	EXTI_PR			(volatile R32_Register *)  (EXTI_BASE + 0x14)

#define 	NVIC_ISER0 		(volatile R32_Register *)0xE000E100

#define		AFIO_EXTICR1	(volatile R32_Register *)  (EXTI_BASE + 0x08)
typedef union {
	vuint32 reg;
	struct{
		vuint32 pin0:1;
		vuint32 pin1:1;
		vuint32 pin2:1;
		vuint32 pin3:1;
		vuint32 pin4:1;
		vuint32 pin5:1;
		vuint32 pin6:1;
		vuint32 pin7:1;
		vuint32 pin8:1;
		vuint32 pin9:1;
		vuint32 pin10:1;
		vuint32 pin11:1;
		vuint32 pin12:1;
		vuint32 pin13:1;
		vuint32 pin14:1;
		vuint32 pin15:1;
		vuint32 pin16:1;
		vuint32 pin17:1;
		vuint32 pin18:1;
		vuint32 pin19:1;
		vuint32 pin20:1;
		vuint32 pin21:1;
		vuint32 pin22:1;
		vuint32 pin23:1;
		vuint32 pin24:1;
		vuint32 pin25:1;
		vuint32 pin26:1;
		vuint32 pin27:1;
		vuint32 pin28:1;
		vuint32 pin29:1;
		vuint32 pin30:1;
		vuint32 pin31:1;
	}pin;
}R32_Register;


int main(void)
{
	(APB2ENR)->pin.pin0 = 1; 		/*Enable Clock For AFIO*/
	(APB2ENR)->pin.pin2 = 1; 		/*Enable Clock For GPIOA*/

	(NVIC_ISER0)->pin.pin6 = 1;

	(GPIOA_CRL)->pin.pin2 = 1;
	(AFIO_EXTICR1)->reg=0;
	(GPIOA_CRH)->reg &= 0xFF0FFFFF; /*Configure PIN13 as output*/
	(GPIOA_CRH)->reg |= 0x00200000;	/*Configure PIN13 as output*/

	(EXTI_IMR)->pin.pin0 = 1;
	(EXTI_RTSR)->pin.pin0 = 1;
	while(1);


	return 0;
}

void EXTI0_IRQHandler()
{
	(EXTI_PR)->pin.pin0 = 1;
	(*GPIOA_ODR).reg ^= 1<<13;
}
